### ISSUE TITLE
erreur a la vérification du .ino

### ISSUE THREAD

**Issue by TownCryer** [bebert0x42/Spool_Measurer#2]
C:\Users\Cedrick\Documents\Arduino\Spool_Measurer\Spool_Measurer.ino:74:10: fatal error: TimerOne.h: No such file or directory
 #include <TimerOne.h>
          ^~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: TimerOne.h: No such file or directory

**Comment by bebert0x42** [comment]
Hello,

Je ferai une réponse plus complète demain et avec la solution mais de mon souvenir : 
Le paquet TimerOne permet d'utiliser un 3 eme timer sur l'arduino. Cependant tout les arduino ne sont pas compatible et il faut être sûr d'avoir le paquet pour compiler.

Plus d'info demain.

**Comment by bebert0x42** [comment]
Du coup c'est bien ça : 
Vérifie que dans le logiciel Arduino tu as bien TimerOne dans tes library (Sketch>>Include Library).
Si tu ne l'as pas, tu peux ajouter cette library dans Manage Librarie (Sketch>>Include Library).
Pour t'aider du à cette vidéo : https://youtu.be/igdBT0hwsJc?t=401
